<a href="https://colab.research.google.com/github/z8899852/DL/blob/master/0326_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 陣列-上課

In [0]:
import numpy as np
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

# 陣列-作業一

In [0]:
import numpy as np
np.tile(np.array([[1,2],[6,7]]),3)

array([[1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7]])

# 陣列-作業二

In [0]:
import numpy as np
np.tile(np.array([[1,2],[6,7]]),(2,2))

array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])

# 陣列-作業三

In [0]:
import numpy as np
np.tile(np.array([[1,2],[6,7]]),3)

array([[1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7]])

# 陣列-作業四

In [0]:
import numpy as np
np.tile(np.array([[1,2],[6,7]]),(2,2))

array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])